// Must only run against a disposable database explicitly named otb_test.
import {test} from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createPool,migrate,syncDirectory} from './database.js';
import {sendBooster,replyBooster,workspace,leaderboard,leaderView} from './domain.js';
import {searchEmployees,listDepartments} from './directory.js';
import {createApplication} from './application.js';
import {createServer} from './server.js';
import {once} from 'node:events';

test('PostgreSQL transactions, concurrency, persistence, HR sync and group scope', {skip:!process.env.TEST_DATABASE_URL}, async t=>{
  const connectionString=process.env.TEST_DATABASE_URL;
  assert.equal(new URL(connectionString).pathname,'/otb_test','Only the disposable test database is allowed');
  const pool=createPool(connectionString);t.after(()=>pool.end());await migrate(pool);
  await pool.query('ALTER TABLE boosters DROP COLUMN recipient_scope');
  await migrate(pool);await migrate(pool);
  const rows=Array.from({length:8},(_,i)=>({USER_ID:`test-${i}`,USER_NM:`가상 구성원 ${i}`,USER_EMAIL:`person${i}@example.invalid`,DEPT_CD:i<4?'test-dept-a':'test-dept-b',DEPT_NM:i<4?'가상 부서 A':'가상 부서 B',ROLE_CD:'',ROLE_NM:''}));
  await syncDirectory(pool,{all:async()=>rows});
  assert.equal((await searchEmployees(pool,new URLSearchParams({q:'가상'}))).total,8);
  assert.equal((await searchEmployees(pool,new URLSearchParams({q:'person1@'}))).data[0].USER_ID,'test-1');
  assert.equal((await searchEmployees(pool,new URLSearchParams({q:'가상',DEPT_CD:'test-dept-a'}),'test-0')).total,3);
  assert.equal((await searchEmployees(pool,new URLSearchParams({q:'%_'}))).total,0);
  assert.equal((await searchEmployees(pool,new URLSearchParams({q:'가상',page:'2'}))).data.length,0);
  assert.equal((await listDepartments(pool)).count,2);
  const input=recipientId=>({recipientId,projectName:'가상 검증 업무',partner:'동료',missions:['문서 작성','평가 및 분석'],boosts:['정보 공유','책임감(R&R)','동료 지지'],impacts:['품질 향상','팀워크 강화'],message:'테스트용 칭찬입니다.'});
  const campaign='test-campaign';
  const requestId=randomUUID();
  const [first,retry]=await Promise.all([sendBooster(pool,'test-0',input('test-1'),requestId,campaign),sendBooster(pool,'test-0',input('test-1'),requestId,campaign)]);
  assert.equal(first.id,retry.id);
  await migrate(pool);
  assert.equal((await workspace(pool,'test-1',campaign)).received[0].recipientScope,null,'Legacy records must not infer scope');
  assert.equal((await sendBooster(pool,'test-0',input('test-1'),requestId,campaign)).replayed,true);
  assert.equal((await workspace(pool,'test-0',campaign)).points,10);
  assert.equal((await workspace(pool,'test-1',campaign)).points,20);
  await assert.rejects(sendBooster(pool,'test-0',{...input('test-1'),message:'different'},requestId,campaign),{code:'IDEMPOTENCY_CONFLICT'});
  await assert.rejects(sendBooster(pool,'test-0',input('test-1'),randomUUID(),campaign),{code:'WEEKLY_LIMIT'});
  await assert.rejects(replyBooster(pool,'test-2',first.id,'가로채기'),{code:'BOOSTER_NOT_FOUND'});
  await Promise.all([replyBooster(pool,'test-1',first.id,'고맙습니다.'),replyBooster(pool,'test-1',first.id,'고맙습니다.')]);
  assert.equal((await workspace(pool,'test-1',campaign)).points,25);
  assert.equal((await workspace(pool,'test-0',campaign)).points,10);
  const attempts=await Promise.allSettled(['test-2','test-3','test-4','test-5'].map(id=>sendBooster(pool,'test-0',input(id),randomUUID(),campaign)));
  assert.equal(attempts.filter(result=>result.status==='fulfilled').length,2);
  assert.equal(attempts.filter(result=>result.status==='rejected'&&result.reason.code==='DAILY_LIMIT').length,2);
  assert.equal((await workspace(pool,'test-0',campaign)).points,30);
  await pool.query('INSERT INTO leader_scopes VALUES($1,$2)',['test-3','test-dept-a']);
  await assert.rejects(leaderView(pool,'test-1',campaign),{code:'LEADER_FORBIDDEN'});
  await assert.rejects(leaderView(pool,'test-3',campaign,'test-7'),{code:'MEMBER_OUT_OF_SCOPE'});
  const group=await leaderView(pool,'test-3',campaign);
  assert.equal(group.members.length,4);
  assert.ok(group.records.every(row=>['test-0','test-1','test-2','test-3'].includes(row.recipientId)));
  const state=await workspace(pool,'test-1',campaign);
  assert.deepEqual(state.received[0].boosts,input('test-1').boosts);
  assert.equal(state.received[0].replyText,'고맙습니다.');
  const ranking=await leaderboard(pool,campaign);
  assert.equal(ranking.scope,'company');assert.equal(ranking.mode,'live');
  assert.ok(ranking.leaders.every(row=>Number.isSafeInteger(row.points)));
  const secondPool=createPool(connectionString);try{assert.equal((await workspace(secondPool,'test-0',campaign)).points,30);}finally{await secondPool.end();}
  await assert.rejects(syncDirectory(pool,{all:async()=>{throw new Error('upstream failed');}}));
  assert.equal((await pool.query('SELECT count(*)::int AS count FROM employees WHERE active')).rows[0].count,8);
  await syncDirectory(pool,{all:async()=>rows.slice(0,7)});
  assert.equal((await pool.query('SELECT active FROM employees WHERE user_id=$1',['test-7'])).rows[0].active,false);
  assert.equal((await workspace(pool,'test-0',campaign)).points,30);
});

test('test-user HTTP workflow is isolated from public ledger and restricts actors and request origin', {skip:!process.env.TEST_DATABASE_URL}, async t=>{
  const url=process.env.TEST_DATABASE_URL;assert.equal(new URL(url).pathname,'/otb_test');
  const publicPool=createPool(url),pool=createPool(url,{testMode:true});
  t.after(async()=>{await pool.end();await publicPool.end();});
  await migrate(publicPool);await migrate(pool,{testMode:true});
  const before=(await publicPool.query('SELECT count(*)::int AS count FROM boosters')).rows[0].count;
  const users=[['preview-a','송재현'],['preview-b','김영훈'],['preview-c','가상 기타']].map(([USER_ID,USER_NM])=>({USER_ID,USER_NM,USER_EMAIL:USER_ID+'@example.invalid',DEPT_CD:'fake',DEPT_NM:'가상 부서',ROLE_NM:'가상 직책'}));
  await syncDirectory(pool,{all:async()=>users});
  const origin='http://preview.invalid';const server=createServer({application:createApplication({pool,testMode:true,previewOrigin:origin})});
  server.listen(0,'127.0.0.1');await once(server,'listening');
  t.after(()=>new Promise(resolve=>{server.close(resolve);server.closeAllConnections();}));
  const base=`http://127.0.0.1:${server.address().port}`;
  const request=(path,id,options={})=>fetch(base+path,{...options,headers:{...(id?{'X-OTB-Test-User':id}:{}),...(options.method?{Origin:origin,'Content-Type':'application/json'}:{}),...options.headers}});
  assert.equal((await (await request('/api/test-users')).json()).data.length,2);
  assert.equal((await request('/api/workspace')).status,401);
  assert.equal((await request('/api/workspace','preview-c')).status,403);
  assert.equal((await request('/api/leader/records','preview-a')).status,403);
  assert.equal((await request('/api/boosters','preview-a',{method:'POST',headers:{Origin:'http://untrusted.invalid'},body:'{}'})).status,403);
  assert.equal((await request('/api/boosters','preview-a',{method:'POST',headers:{Origin:''},body:'{}'})).status,403);
  const search=await (await request('/api/employees?q='+encodeURIComponent('김영훈'),'preview-a')).json();assert.equal(search.data[0].USER_ID,'preview-b');
  const body={recipientId:'preview-b',projectName:'가상 검증',partner:'동료',recipientScope:'타팀',missions:['문서 작성'],boosts:['정보 공유','동료 지지'],impacts:['품질 향상'],message:'가상 테스트 메시지'};
  const options={method:'POST',headers:{'Idempotency-Key':randomUUID()},body:JSON.stringify(body)};
  const first=await request('/api/boosters','preview-a',options);assert.equal(first.status,201);const sent=await first.json();
  const again=await (await request('/api/boosters','preview-a',options)).json();assert.equal(sent.id,again.id);
  const state=async id=>(await request('/api/workspace',id)).json();
  assert.equal((await state('preview-a')).sentBoosters[0].recipientScope,'타팀');assert.equal((await state('preview-b')).received[0].recipientScope,'타팀');
  const changed=await request('/api/boosters','preview-a',{...options,body:JSON.stringify({...body,recipientScope:'같은팀'})});assert.equal(changed.status,409);
  assert.equal((await state('preview-a')).points,10);assert.equal((await state('preview-b')).points,20);
  const reply={method:'POST',body:JSON.stringify({message:'가상 답장'})};
  assert.equal((await request('/api/boosters/'+sent.id+'/reply','preview-a',reply)).status,404);
  assert.equal((await request('/api/boosters/'+sent.id+'/reply','preview-b',reply)).status,200);
  assert.equal((await request('/api/boosters/'+sent.id+'/reply','preview-b',reply)).status,200);
  assert.equal((await state('preview-b')).points,25);
  const ranking=await (await request('/api/leaderboard','preview-a')).json();assert.equal(ranking.scope,'test');assert.equal(ranking.mode,'test');
  assert.equal((await publicPool.query('SELECT count(*)::int AS count FROM boosters')).rows[0].count,before);
  assert.equal((await pool.query('SELECT current_schema() AS name')).rows[0].name,'otb_preview');
  const info=await (await request('/api/system')).json();assert.equal(info.testUserMode,true);assert.equal(info.capabilities.authentication,false);assert.equal(info.productionReady,false);
});
